[package]
name = "rust-gameboy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.23"
rand = "0.8.4"
spin_sleep = "1.1.1"